# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f852a7b4333511525810c15bc271f79310722da7823357fa2c8e3ae29800824d08ef1f6f033a83c997262ee7731a4ef7bee7c000e39512805c2395ddab86bff3

test:
  secret_key_base: 36ea9ef67b51661feb1eeaa23a1e45ce4ca3daafb03de948c7f0448fcd2528c1c74c254ec8ec7aee4ffc455d652e21f0c46d4c8785c1588efd2596e64bbf3e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
